version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '7000:7000'
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    restart: always
    container_name: frontend
